### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by LCMAIA** [Dave1001/OpenSprinkler-Arduino#1]
I liked a lot your work with opensplinker. Thanks. There are a new fork of a new version?

thanks

**Comment by Dave1001** [comment]
Hi!

Apologies I've been very slack reading these messages on Github - I uploaded a new version about 6 months ago. Maybe every couple of months I have a look to see what Ray's updated (as of today its still 2.1.6 which is same as version I'm using)

Cheers
