### ISSUE TITLE
ESP8266 fork

### ISSUE THREAD

**Issue by pbecchi** [Dave1001/OpenSprinkler-Arduino#2]
Hello Dave
I have downloaded yourOPENSPRIKLERARDUINO  2.1.6 code and I am trying to port it to ESP 8266.
This his the shortest way to get an OpenSprinkler on ESP.
If you are interest I may upload this as a fork to your master-code.
I have few questions on difference between original version and your code (mainly on button settings: you have 5 in place of 3.... there is any documentation on how they work?)
Thanks
Paolo

**Comment by Dave1001** [comment]
Hi there Paolo

 

Thanks for your email – I have to admit I was slack and hadn’t uploaded the new code to github until just now – if you go there now you’ll see new code uploaded for opensprinkler version 2.1.6

 

I’ve not used an ESP 8266, but based on experience from playing with Rays original code I’d suggest it may be easier to port the network server code from the Raspberry Pi version of opensprinkler (the ethercard library used by the Arduiino for ENC38J60 is not nice)

 

Anyway – all the best of luck!

 

Dave

**Comment by pbecchi** [comment]
Dave thank for your advices...
I think that I have already done most of the work (at least I hope..) with your code and I must say that the  c++ code as not the main difficulty since I am using the Arduino ESP8266 core libraries.
The major challange is to use the fe GPIO available and accomplish all the functions.
I am using shift registers, an I2C LCD and your analog input system (4 button rather than 5).
I have tried to make a trasparent mod using ....#ifdef ESP8266.. so that the code should keep working on an Arduino mega.
I am starting now the debug fase....... hat about your tests?

Paolo

**Comment by pbecchi** [comment]
Dave thank for your advices...
I think that I have already done most of the work (at least I hope..) with your code and I must say that the  c++ code as not the main difficulty since I am using the Arduino ESP8266 core libraries.
The major challange is to use the fe GPIO available and accomplish all the functions.
I am using shift registers, an I2C LCD and your analog input system (4 button rather than 5).
I have tried to make a trasparent mod using ....#ifdef ESP8266.. so that the code should keep working on an Arduino mega.
I am starting now the debug fase....... what about your tests?

Paolo 
ps sorry I have a terrible keyboard ... very often  2,w dont come out......

**Comment by pbecchi** [comment]
Dave thank for your advices...
I think that I have already done most of the work (at least I hope..) with your code and I must say that the  c++ code as not the main difficulty since I am using the Arduino ESP8266 core libraries.
The major challange is to use the fe GPIO available and accomplish all the functions.
I am using shift registers, an I2C LCD and your analog input system (4 button rather than 5).
I have tried to make a trasparent mod using ....#ifdef ESP8266.. so that the code should keep working on an Arduino mega.
I am starting now the debug fase....... what about your tests?

Paolo 
ps sorry I have a terrible keyboard ... very often  2,w dont come out......

**Comment by pbecchi** [comment]
Dave thank for your advices...
I think that I have already done most of the work (at least I hope..) with your code and I must say that the  c++ code as not the main difficulty since I am using the Arduino ESP8266 core libraries.
The major challange is to use the fe GPIO available and accomplish all the functions.
I am using shift registers, an I2C LCD and your analog input system (4 button rather than 5).
I have tried to make a trasparent mod using ....#ifdef ESP8266.. so that the code should keep working on an Arduino mega.
I am starting now the debug fase....... what about your tests?

Paolo 
ps sorry I have a terrible keyboard ... very often  2,w dont come out......

**Comment by pbecchi** [comment]
Dave thank for your advices...
I think that I have already done most of the work (at least I hope..) with your code and I must say that the  c++ code as not the main difficulty since I am using the Arduino ESP8266 core libraries.
The major challange is to use the fe GPIO available and accomplish all the functions.
I am using shift registers, an I2C LCD and your analog input system (4 button rather than 5).
I have tried to make a trasparent mod using ....#ifdef ESP8266.. so that the code should keep working on an Arduino mega.
I am starting now the debug fase....... what about your tests?

Paolo 
ps sorry I have a terrible keyboard ... very often  2,w dont come out......

**Comment by pbecchi** [comment]
Dave thank for your advices...
I think that I have already done most of the work (at least I hope..) with your code and I must say that the  c++ code as not the main difficulty since I am using the Arduino ESP8266 core libraries.
The major challange is to use the fe GPIO available and accomplish all the functions.
I am using shift registers, an I2C LCD and your analog input system (4 button rather than 5).
I have tried to make a trasparent mod using ....#ifdef ESP8266.. so that the code should keep working on an Arduino mega.
I am starting now the debug fase....... what about your tests?

Paolo 
ps sorry I have a terrible keyboard ... very often  2,w dont come out......

**Comment by pbecchi** [comment]
Dave thank for your advices...
I think that I have already done most of the work (at least I hope..) with your code and I must say that the  c++ code as not the main difficulty since I am using the Arduino ESP8266 core libraries.
The major challange is to use the fe GPIO available and accomplish all the functions.
I am using shift registers, an I2C LCD and your analog input system (4 button rather than 5).
I have tried to make a trasparent mod using ....#ifdef ESP8266.. so that the code should keep working on an Arduino mega.
I am starting now the debug fase....... what about your tests?

Paolo 
ps sorry I have a terrible keyboard ... very often  2,w dont come out......

**Comment by pbecchi** [comment]
Dave thank for your advices...
I think that I have already done most of the work (at least I hope..) with your code and I must say that the  c++ code as not the main difficulty since I am using the Arduino ESP8266 core libraries.
The major challange is to use the fe GPIO available and accomplish all the functions.
I am using shift registers, an I2C LCD and your analog input system (4 button rather than 5).
I have tried to make a trasparent mod using ....#ifdef ESP8266.. so that the code should keep working on an Arduino mega.
I am starting now the debug fase....... what about your tests?

Paolo 
ps sorry I have a terrible keyboard ... very often  2,w dont come out......

**Comment by pbecchi** [comment]
Dave thank for your advices...
I think that I have already done most of the work (at least I hope..) with your code and I must say that the  c++ code as not the main difficulty since I am using the Arduino ESP8266 core libraries.
The major challange is to use the fe GPIO available and accomplish all the functions.
I am using shift registers, an I2C LCD and your analog input system (4 button rather than 5).
I have tried to make a trasparent mod using ....#ifdef ESP8266.. so that the code should keep working on an Arduino mega.
I am starting now the debug fase....... what about your tests?

Paolo 
ps sorry I have a terrible keyboard ... very often  2,w dont come out......

**Comment by pbecchi** [comment]
Dave thank for your advices...
I think that I have already done most of the work (at least I hope..) with your code and I must say that the  c++ code as not the main difficulty since I am using the Arduino ESP8266 core libraries.
The major challange is to use the fe GPIO available and accomplish all the functions.
I am using shift registers, an I2C LCD and your analog input system (4 button rather than 5).
I have tried to make a trasparent mod using ....#ifdef ESP8266.. so that the code should keep working on an Arduino mega.
I am starting now the debug fase....... what about your tests?

Paolo 
ps sorry I have a terrible keyboard ... very often  2,w dont come out......

**Comment by pbecchi** [comment]
Dave thank for your advices...
I think that I have already done most of the work (at least I hope..) with your code and I must say that the  c++ code as not the main difficulty since I am using the Arduino ESP8266 core libraries.
The major challange is to use the fe GPIO available and accomplish all the functions.
I am using shift registers, an I2C LCD and your analog input system (4 button rather than 5).
I have tried to make a trasparent mod using ....#ifdef ESP8266.. so that the code should keep working on an Arduino mega.
I am starting now the debug fase....... what about your tests?

Paolo 
ps sorry I have a terrible keyboard ... very often  2,w dont come out......

**Comment by pbecchi** [comment]
Dave thank for your advices...
I think that I have already done most of the work (at least I hope..) with your code and I must say that the  c++ code as not the main difficulty since I am using the Arduino ESP8266 core libraries.
The major challange is to use the fe GPIO available and accomplish all the functions.
I am using shift registers, an I2C LCD and your analog input system (4 button rather than 5).
I have tried to make a trasparent mod using ....#ifdef ESP8266.. so that the code should keep working on an Arduino mega.
I am starting now the debug fase....... what about your tests?

Paolo 
ps sorry I have a terrible keyboard ... very often  2,w dont come out......

**Comment by pbecchi** [comment]
Dave thank for your advices...
I think that I have already done most of the work (at least I hope..) with your code and I must say that the  c++ code as not the main difficulty since I am using the Arduino ESP8266 core libraries.
The major challange is to use the fe GPIO available and accomplish all the functions.
I am using shift registers, an I2C LCD and your analog input system (4 button rather than 5).
I have tried to make a trasparent mod using ....#ifdef ESP8266.. so that the code should keep working on an Arduino mega.
I am starting now the debug fase....... what about your tests?

Paolo 
ps sorry I have a terrible keyboard ... very often  2,w dont come out......

**Comment by pbecchi** [comment]
Dave thank for your advices...
I think that I have already done most of the work (at least I hope..) with your code and I must say that the  c++ code as not the main difficulty since I am using the Arduino ESP8266 core libraries.
The major challange is to use the fe GPIO available and accomplish all the functions.
I am using shift registers, an I2C LCD and your analog input system (4 button rather than 5).
I have tried to make a trasparent mod using ....#ifdef ESP8266.. so that the code should keep working on an Arduino mega.
I am starting now the debug fase....... what about your tests?

Paolo 
ps sorry I have a terrible keyboard ... very often  2,w dont come out......

**Comment by pbecchi** [comment]
Dave thank for your advices...

I think that I have already done most of the work (at least I hope..) with your code and I must say that the  c++ has not been the main difficulty since I am using the Arduino ESP8266 core libraries.
The major challenge is to use the few GPIO available and accomplish all the functions.
I am using shift registers, an I2C LCD and your analog input system (4 button rather than 5).
I have tried to make a trasparent mod using ....#ifdef ESP8266.. so that the code should keep working on an Arduino mega.
I am starting now the debug fase....crossing fingers.............................. what about your tests?

I have seen the note about the use of more button at the same time...
how you accomplish those function ? 
With the additional 2 buttons?


Paolo 

ps sorry I have a terrible keyboard ... very often  2,w dont come out......
Messaggio inviato dal mio ASUS Pad

Dave1001 <notifications@github.com> ha scritto:

**Comment by Dave1001** [comment]
Hi Paolo

That's really interesting - it's the first time I've looked at an Esp8266 and it looks like a great little chip

One thing that may help (or you may have solved this already) is a while back I set up an arduino nano as an I2C slave so I could access more hardware UARTS. It was a horribly wasteful use of good micro's but very cheap ($4), only uses two wires, and less hassle than buying chips and soldering them to a breakout.....

Sooo - would be trivial to convert that code to be an I2C to GPIO bridge, to replace the shift register with an arduino nano or similar / kind of like using a nano as a cheap I2C addressable GPIO module

 The idea would be to connect the ESP 8266 to both your LCD and GPIO (via a nano) on same two wire interface 

Let me know your thoughts? I'm away for a couple of days but happy to dust off the code when I'm back at the end of the week and put it on GitHub 

Lastly - on the buttons - you'll see in the source code I just disabled any functions needing two button presses / the reason is I never use the LCD or buttons as the iPad app is heaps easier to control. Right now I don't even have an LCD on the opensprinkler as its just not necessary (the only reason I bother connecting one is for testing new code)

Cheers

**Comment by pbecchi** [comment]
Hi Dave

That's exactely what I am doing now. My second prototype board
use I2C for GPIO expansion:
- I use a PCF8574A IC  in place of the 75SN595
- the shift register code it is simply replaced with a wire.write to the unit of the bitmask.
-now I have LCD ,stations I/O, RTC and EEPROM all in two wires

This way I have all the other pins available (6 digital + 1 analog).
I can be able to use all opensprinkler functions (flow reading, remote control, rain  and other sensor reading).

It could be usefull to exchange experience and difficulties on debugging and testing the unit.
   Since 2-3 day my unit work without break (restart at the moment doesnt work!?) .....I have problems with the functions of the weather connections (DST and time zone and weather data) but it may be due to not having created a new weather underground key.
 
I have tried to contanct Ray of Opensprinkler.com to inform him on what I am doing.

....no replay so far....

Keep in contact and.......
 thanks!


Paolo

 
Messaggio inviato dal mio ASUS Pad

Dave1001 <notifications@github.com> ha scritto:

>Hi Paolo
>
>That's really interesting - it's the first time I've looked at an Esp8266 and it looks like a great little chip
>
>One thing that may help (or you may have solved this already) is a while back I set up an arduino nano as an I2C slave so I could access more hardware UARTS. It was a horribly wasteful use of good micro's but very cheap ($4), only uses two wires, and less hassle than buying chips and soldering them to a breakout.....
>
>Sooo - would be trivial to convert that code to be an I2C to GPIO bridge, to replace the shift register with an arduino nano or similar / kind of like using a nano as a cheap I2C addressable GPIO module
>
> The idea would be to connect the ESP 8266 to both your LCD and GPIO (via a nano) on same two wire interface 
>
>Let me know your thoughts? I'm away for a couple of days but happy to dust off the code when I'm back at the end of the week and put it on GitHub 
>
>Lastly - on the buttons - you'll see in the source code I just disabled any functions needing two button presses / the reason is I never use the LCD or buttons as the iPad app is heaps easier to control. Right now I don't even have an LCD on the opensprinkler as its just not necessary (the only reason I bother connecting one is for testing new code)
>
>Cheers
>
>Sent from my iPad
>
