### ISSUE TITLE
Relay HIGH/LOW.

### ISSUE THREAD

**Issue by chinaryov** [Dave1001/OpenSprinkler-Arduino#4]
Hello,

Thank you for your effort. It is really helped me to set-up and run the watering system.
For relay board I'm using some kind of this - http://www.ebay.com/itm/16-Channel-Relay-12V-Module-for-Arduino-UNO-MEGA2560-R3-Raspberry-Pi-Opto-couple-/281467026037
But I had to change the code for this board:
...w5100/OpenSprinkler.cpp line 829
from: digitalWrite ( station_pins[ ( bid * 8 ) + s], ( sbits & ( ( byte ) 1 << s ) ) ? HIGH: LOW );
to: digitalWrite ( station_pins[ ( bid * 8 ) + s], ( sbits & ( ( byte ) 1 << s ) ) ? LOW: HIGH );

Are there any other options to solve my problem?
What relay board are you using?

**Comment by Dave1001** [comment]
Hi

Apologies I've been very slack reading these messages on Github - you've made exactly the change that I would have!

Looks like the relay board you're using is very similar to the one I have (mines also opto isolated like this one http://www.ebay.com/itm/8-Channel-DC-5V-Relay-Module-for-Arduino-Raspberry-Pi-DSP-AVR-PIC-ARM-/191674534102?hash=item2ca0b148d6:g:cbkAAOxyIYhSY9pn ) - not sure why the logic is different though. Go figure / maybe we should add a #define switch to make it easier to invert.

Cheers

**Comment by Dave1001** [comment]
Just added a #define switch in Config.h to make it easier to invert.
